name: PSY9511_env
channels:
  - defaults
dependencies:
  - matplotlib
  - jupyter
  - seaborn
  - python=3.11
  - numpy
  - pandas
  - scikit-learn
  - pytorch
  - torchvision
  - pytorch-lightning
  - pip
  - pip:
    - ISLP
    - torchmetrics
    - torchinfo
